### ISSUE TITLE
Ogg files cut short

### ISSUE THREAD

**Issue by GallantArc302** [FelixdelasPozas/OGG-Extractor#7]
I've tried this with [FNF Indie Cross](https://gamejolt.com/games/indiecross/643540) which has some of the music embedded into the exe, I'm also pretty sure it happens with other games too.
I used a separate program to extract the ogg files first with a specific length since I don't know how to find the real length, but it merged some of the ogg files in the process. Audacity automatically cut out the extra data (game code, images, etc) when opening them, but can't fix the merged issue without reexporting.
When I tried this program, I compared it to those files and they were shorter than the [full length ones.](https://cdn.discordapp.com/attachments/816370637379207198/981798306197950494/Indie_Cross_00000000.zip)

**Comment by FelixdelasPozas** [comment]
Hi @garc302 .

OGG-Extractor just searchs for ogg file headers and extracts the file with the length that the header tells it to. Audacity seems to also look at the header and just load the correct data and discard the rest, that's why in your *full length ones* it can load file number 003 (I think that is the 33 seconds one) correctly. 

![Clipboard01](https://user-images.githubusercontent.com/12167134/171789867-36b3f05f-b3a8-41af-a59b-2e7db3124532.png)

Using OGG-Extractor with the downloadable version of FNF Indie Cross gives me 8 files embedded within the exe. Listening to them all before extracting they all seem to be correct (the last two are really short, less than a second, maybe 'click' sounds for the menus?). It just extracts the files **as they are** embedded in the executable.

The problem with game audio is that sometimes some editing is needed if you want a song out of it. For example in this case the 33 seconds file seems to end abruptly but it's just that probably in-game that file has an endless loop (and probably a fade-out? I haven't played the game). Looks like it's menu music. As you don't know how many time the user will be in the menus (could be a few seconds or a few minutes) you'll just loop the end part. 

Regards, 
Felix.

**Comment by FelixdelasPozas** [comment]
Closing the issue as it doesn't seem to be a bug or anything similar, just a misunderstanding about how OGG-Extractor works.
